create database library;
use library;
create table BOOKS (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    DATE_ADDED DATETIME DEFAULT CURRENT_TIMESTAMP,
    AUTHOR VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
 );
